---
_prometheus_go_ansible_arch: "{{ {'i386': '386',
                              'x86_64': 'amd64',
                              'aarch64': 'arm64',
                              'armv7l': 'armv7',
                              'armv6l': 'armv6'}.get(ansible_architecture, ansible_architecture) }}"
_prometheus_binary_install_dir: '/usr/local/bin'

_prometheus_repo: "prometheus/prometheus"
_github_api_headers: "{{ {'GITHUB_TOKEN': lookup('ansible.builtin.env', 'GITHUB_TOKEN')} if (lookup('ansible.builtin.env', 'GITHUB_TOKEN')) else {} }}"
_prometheus_binaries:
  - prometheus
  - promtool
